### ISSUE TITLE
Can not get the function URL when deploying bitcoin-info-action to firebase

### ISSUE THREAD

**Issue by srm60** [greenido/bitcoin-info-action#3] opened 2017-12-30 01:14 UTC
I am deploying https://github.com/greenido/bitcoin-info-action with instructions from https://codelabs.developers.google.com/codelabs/your-first-action-on-google-with-webhook/#0

When I use the Webhook URL provided in the example, it works fine. When I build and deploy using the code myself for the webhook , it does not generate function URL.

Here are the steps:

Clone the Git Repo https://github.com/greenido/bitcoin-info-action
Do a firebase init Do a firebase deploy (install all modules as needed)
I have not changed the index.js , reviewed the answers at Can't find the function url for Firebase webhook in Google Assistant tutorial and others.
I have checked the firebase console and functions on the left menu and I do not find a URL, instead instructions on deploy (same that I used )

Here is the output of firebase deploy:

[google-tester-mn1:~/soverflow/bitcoin-info-action-master ] $ /Users/google-tester/.nvm/versions/node/v9.3.0/lib/node_modules/firebase-tools/bin/firebase deploy

=== Deploying to 'bitcoininfo-5cb78'...

i  deploying functions, hosting
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  hosting: preparing public directory for upload...
✔  hosting: 2 files uploaded successfully

✔  Deploy complete!

Project Console: https://console.firebase.google.com/project/bitcoininfo-5cb78/overview
Hosting URL: https://bitcoininfo-5cb78.firebaseapp.com
Here is the output of deploy --only functions:

Deploying to 'bitcoininfo-5cb78'...

i  deploying functions
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

 ✔  Deploy complete!

 Project Console: https://console.firebase.google.com/project/bitcoininfo-5cb78/overview
Contents of the directory:

[google-tester-mn1:~/soverflow/bitcoin-info-action-master/functions ] $ ls -l ~/soverflow/bitcoin-info-action-master
total 96
-rwxr-xr-x@ 1 google-tester  google-tester   1642 Nov 16 17:04 CONTRIBUTING.md
-rwxr-xr-x@ 1 google-tester  google-tester  11325 Nov 16 17:04 LICENSE
-rwxr-xr-x@ 1 google-tester  google-tester   3255 Nov 16 17:04 README.md
-rw-r--r--@ 1 google-tester  google-tester    796 May  1  2017 agent.json
-rw-r--r--@ 1 google-tester  google-tester   3865 Nov 16 17:04 bitcoin-info-io17.zip
-rw-r--r--  1 google-tester  google-tester    134 Dec 29 11:42 firebase.json
drwxr-xr-x  6 google-tester  google-tester    204 Dec 29 12:31 functions
-rwxr-xr-x@ 1 google-tester  google-tester   4411 Nov 16 17:04 index.js
drwxr-xr-x@ 7 google-tester  google-tester    238 Dec 29 11:39 intents
-rwxr-xr-x@ 1 google-tester  google-tester    647 Nov 16 17:04 package.json
drwxr-xr-x  4 google-tester  google-tester    136 Dec 29 11:42 public
-rwxr-xr-x@ 1 google-tester  google-tester   2476 Nov 16 17:04 webhook-example-bitcoin.php

Again:
[google-tester-mn1:~/soverflow/bitcoin-info-action-master/functions ]ls -l ~/soverflow/bitcoin-info-action-master/functions/
total 576
-rw-r--r--@   1 google-tester  google-tester    4411 Dec 29 12:23 index.js
drwxr-xr-x  124 google-tester  google-tester    4216 Dec 29 12:24 node_modules
-rw-r--r--    1 google-tester  google-tester  281603 Dec 29 12:24 package-lock.json
-rw-r--r--    1 google-tester  google-tester     460 Dec 29 12:24 package.json

I have all the node modules, including actions-on-google. There is no error about missing modules.

**Comment by afirstenberg** [comment] 2018-01-01 16:01
The issue is that this code is written to use Google Cloud Functions and you're trying to use it with Cloud Functions for Firebase.

See [Pull Request #4](https://github.com/greenido/bitcoin-info-action/pull/4) for a solution.

**Comment by srm60** [comment] 2018-01-01 21:59
I have verified that this works perfectly. Thanks!

**Comment by greenido** [comment] 2018-01-02 03:23
Thank you both! The fixed is now merged!

**Closed as completed by greenido** 2018-01-02 03:23 UTC
